### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'FontDialog'

### ISSUE THREAD

**Issue by GeoRW** [mizaki/acbf_editor#1]
Hi mate,

I'm the original developer of ACBF format and tools. I see you did some work on ACBF Editor here. I did the similar work recently, not knowing you had this repo here. I also ported app for Android, GTK Viewer was already done earlier. I migrated repos from Launchpad to GitHub, you can find here: https://github.com/GeoRW/ACBF
So, maybe we can combine this work, if you're interested. Would be good to have all repos under one umbrella.

I tried to run ACBF Editor from your repo, but unfortunately I was not able to run it on my system as Gtk.FontDialog is available only since: 4.10. So, would be good to have a fallback to custom font dialog, if it's not available.
Another thing I noticed, is that you commented out all the CV stuff (detect bubbles, frames). I have this working in my repo (https://github.com/GeoRW/ACBF-Editor). CV algorhitm is not state of the art, but helps me a lot when I'm working on some comic book. Could be improved to use code from some other project I saw here on GitHub to do comic page segmentation or some other way.

I went on hiatus for couple of years (busy with family, bulding a house ...), but came back to revive the project. It's good that someone did some work here. Not sure if I will have much time for it, but so far I ported everything to Python 3 and PYGObject, so that it works and Android app needed to comply with new Android Shared Storage concept, so I did the work there and published APK with release 2.0. There was also web with ACBF Books which died when they started to change me on IBM Cloud and didn't have time to move it elsewhere. So, maybe that's what I will look at next.

Cheers,
Robert

**Comment by mizaki** [comment]
Hey!

So, I searched and I searched for you!

This was still a WIP and here mostly as a backup.

The font thing is a pain (system versus "local") and I have done a bit more work on it not committed yet (also lint etc.).

I'm more than happy to close this down and see about merging in changes etc. I'll check out your work (and try not to shout about any duplicated work) and do PRs etc. on your repo.

If you are on Discord you can find me in the Mylar server: https://discord.gg/WsqQkwSy

**Comment by GeoRW** [comment]
Ok, cool. Your code is better structured and you did lot of improvements there, so I would prefer your version over the patched old one, once it's ready. I granted you access to my repo directly. I'm on Ubuntu 22.04, so some code may not work on my side, but I can test it and fix once you're done with your work.
And maybe I need to consider upgrading finally :-)

**Comment by mizaki** [comment]
I've pushed an update which is uses only the Fonts dir currently. It still needs some thought with fallback and system fonts etc.

**Comment by GeoRW** [comment]
Still cannot run it as my GTK 4 is version 4.6.9 and even FileDialog is 4.10 onwards. So, let's keep your stuff >=4.10, you don't have to bother to fallback to custom dialogs. I will need to upgrade my system anyway.

**Comment by mizaki** [comment]
Okay. I've checked and 4.10 is the highest version method I've used.

I've corrected the version checks so if you can check it errors correctly (although it might have been before)?
